version: '3.9'
services:
  memcached:
    container_name: memcached
    image: memcached
    ports:
      - 11211:11211

  server:
    build: .
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - memcached
